### ISSUE TITLE
[IMPROVEMENT | DOCUMENTATION] 

### ISSUE THREAD

**Issue by truly-indian** [shahab65/next-kepler-gl#1]
Can you please update the readme.md with the proper documentation. For examples the steps need to run this project in local. I am facing a lot of issues with it while running it in local. It would be really helpfull if you could plz help us with the the exact node version you used for developing this projec.t

**Comment by shahab65** [comment]
Hello @truly-indian 
This repository is related to this article:
https://dev.to/shahab65/adding-kepler-gl-to-a-nextjs-application-3l7k
Please read this step-by-step guide and let me know if you still have any problems
